### ISSUE TITLE
General Discussion

### ISSUE THREAD

**Issue by StatMixedML** [StatMixedML/LightGBMLSS#1]
# Summary
Referencing to this issue https://github.com/StatMixedML/CatBoostLSS/issues/5#issue-648885767

@jrzaurin Let`s continue the discussion on this repo.

**Comment by javier-cazana** [comment]
Whenever you have a working version we are ready to test it on our data, just so you know :)

**Comment by javier-cazana** [comment]
@StatMixedML HI Alexander, I was wondering what would be the best way of asking you about your paper. I have read it but I am not a statistician, so there are a few parts where I am bit lost. To be honest mostly regarding the description of the algorithm in page 7. 

My email is jrzaurin@gmail.com. If you prefer I can post here🙂

**Comment by StatMixedML** [comment]
@javier-cazana You can also post your questions here, no problem
