### ISSUE TITLE
IndexError: LightGBMLSS.train(valid_sets=[dataset_val]) calls set_valid_margin, which seems to expect both train+val 

### ISSUE THREAD

**Issue by ninist** [StatMixedML/LightGBMLSS#31]
I call LightGBMLSS.train like this
```
early_stop = 20
dataset_params = {"feature_pre_filter": False}
dataset_train = lightgbm.Dataset(
    train_X,
    train_y["value"].ravel(),
    free_raw_data=False,
    params=dataset_params,
)
dataset_val = lightgbm.Dataset(
    val_X,
    val_y["value"].ravel(),
    free_raw_data=False,
    params=dataset_params,
)

distribution = lightgbmlss.model.LightGBMLSS(
    lightgbmlss.distributions.Gaussian.Gaussian(
        stabilization="None",
        response_fn="exp",
        loss_fn="nll",
    )
)

distribution.train(
    params=my_hyperparams,
    num_boost_round=9999999, # early_stopping should kick in before this
    train_set=dataset_train,
    valid_sets=[dataset_val],
    callbacks=[
        lightgbm.early_stopping(early_stop, verbose=False),
        lightgbm.log_evaluation(-1),
    ],
)
```

It results in this error
```
File ~/miniconda3/envs/package_name/lib/python3.9/site-packages/lightgbmlss/model.py:575, in LightGBMLSS.set_valid_margin(self, valid_sets, start_values)
    572 init_score_val1 = (np.ones(shape=(valid_sets1.get_label().shape[0], 1))) * start_values
    573 valid_sets1.set_init_score(init_score_val1.ravel(order="F"))
--> 575 valid_sets2 = valid_sets[1]
    576 init_score_val2 = (np.ones(shape=(valid_sets2.get_label().shape[0], 1))) * start_values
    577 valid_sets2.set_init_score(init_score_val2.ravel(order="F"))

IndexError: list index out of range
```

https://github.com/StatMixedML/LightGBMLSS/blob/master/lightgbmlss/model.py#L559-L579
It seems `set_valid_margin` expects both the training set and the validation set as parameters, but later when `lgb.train` is called, the same list is passed in as `valid_sets`, in addition to the training set via `train_set` as the first parameter:
https://github.com/StatMixedML/LightGBMLSS/blob/master/lightgbmlss/model.py#L171-L177

Have I misunderstood when I think this will cause the training set to be used as a validation set for early stopping (which may not be desirable) ?

**Comment by ninist** [comment]
It may also have unexpected behaviour if passed in several - for example 10 - validation sets, as it only processes the first two in the list.

**Comment by StatMixedML** [comment]
Thanks for your interest in the project. I am on vacation until end of October, so please expect some delay in my reply.

**Comment by StatMixedML** [comment]
@ninist Sorry for the very late response. 

The initial code assumed that there are always two datasets in eval_sets. However, as you pointed out, it makes more sense to loop over the list so that it is also possible to have only one dataset in the list. I pushed the changes, using your suggested code

```python
 for valid_set in valid_sets:
        self.set_init_score(valid_set)
```

**Comment by StatMixedML** [comment]
@ninist Can I close this?

**Comment by ninist** [comment]
Sure, thanks - I assume there is no issue by calling `set_init_score` twice on the training set if it happens to be included in the list of validation sets too? (once at the start of train() and then again during set_valid_margins)

**Comment by StatMixedML** [comment]
> Sure, thanks - I assume there is no issue by calling set_init_score twice on the training set if it happens to be included in the list of validation sets too? (once at the start of train() and then again during set_valid_margins)

It shouldn't since it is only over-writing the existing values again.
