### ISSUE TITLE
May I ask if there is a plan to develop  C++ API?

### ISSUE THREAD

**Issue by JiangWeiHn** [StatMixedML/LightGBMLSS#44]
I am trying to use this model to predict the IMU constant bias in SLAM. The program is developed using C++, so I have this request。

**Comment by StatMixedML** [comment]
@JiangWeiHn Thanks for your interest in the project.

At the moment I am not planning to add a C++ APi.

**Comment by JiangWeiHn** [comment]
thanks for reply
