### ISSUE TITLE
[Feature request] latest lightgbm support

### ISSUE THREAD

**Issue by apiss2** [StatMixedML/LightGBMLSS#6]
The latest version of lightgbm (v3.3.4) removes fobj from the train argument of the trainingAPI and does not seem to work.
Is there any plan to support the latest version of lightgbm?

**Comment by StatMixedML** [comment]
Thanks for your interest in the project.

I am planning to release a revised version of both XGBoostLSS and LightGBMLSS soonish, including support for latest versions. But not sure when I find the time.

**Comment by apiss2** [comment]
Thank you for taking the time out of your busy schedule to reply!

We look forward to the day when this wonderful library will be available in the latest version of lgbm.
